### ISSUE TITLE
RuntimeError: shape '[512]' is invalid for input of size 0

### ISSUE THREAD

**Issue by noorkaif97** [cfotache/pytorch_custom_yolo_training#8]
Hi,

I am getting the below error message while running the train.py file. Please help me in correcting it.
Thanks in advance.

Complete error message:

Traceback (most recent call last):
  File "train.py", line 58, in <module>
    model.load_weights(opt.weights_path)
  File "/content/pytorch_custom_yolo_training/models.py", line 297, in load_weights
    bn_b = torch.from_numpy(weights[ptr : ptr + num_b]).view_as(bn_layer.bias)
RuntimeError: shape '[512]' is invalid for input of size 0

**Comment by noorkaif97** [comment]
There error was caused due to the issue in the weights.
